import { CertificateDto } from 'src/certificate/dto/create-certificate.dto'

export const getHtml = async (dto: CertificateDto): Promise<string> => {
	switch (dto.templateId) {
		case 1:
			return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Marck+Script&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"><title>Certificate</title><style type="text/css">@page{size:A5 landscape;margin:0}.marck-script-regular{font-family:'Marck Script',cursive;font-weight:400;font-style:normal}.roboto-light{font-family:Roboto,sans-serif;font-weight:300;font-style:normal}.roboto-regular{font-family:Roboto,sans-serif;font-weight:400;font-style:normal}.roboto-bold{font-family:Roboto,sans-serif;font-weight:700;font-style:normal}*{margin:0;padding:0;box-sizing:border-box}html{background:#eee}body{box-sizing:border-box;height:148mm;width:210mm;background-image:url("http://localhost:4200/static/images/img/bg-certificate.jpg");background-repeat:no-repeat;background-size:cover;background-position:center center;margin:0;display:flex;justify-content:center;padding-top:55mm;position:relative}.wrapper{display:flex;flex-direction:column;align-items:center}.title{font-size:48px;margin-bottom:20px}.qr{width:90px;height:90px;position:absolute;left:21px;bottom:21px}.price{font-size:68px;color:#ab2200;padding-left:16px}.price span{font-size:32px}</style></head><body><div class="wrapper"><h1 class="marck-script-regular title">${dto.title}</h1><h2 class="roboto-bold price">${dto.totalPrice}<span>₽</span></h2></div><img class="qr" src="http://localhost:4200/static/images/qr/${dto.id}.png" alt=""></body></html>`
		case 2:
			return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Marck+Script&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"><title>Certificate</title><style type="text/css">@page{size:A5 landscape;margin:0}.marck-script-regular{font-family:'Marck Script',cursive;font-weight:400;font-style:normal}.roboto-light{font-family:Roboto,sans-serif;font-weight:300;font-style:normal}.roboto-regular{font-family:Roboto,sans-serif;font-weight:400;font-style:normal}.roboto-bold{font-family:Roboto,sans-serif;font-weight:700;font-style:normal}*{margin:0;padding:0;box-sizing:border-box}html{background:#eee}body{box-sizing:border-box;height:148mm;width:210mm;background-image:url("http://localhost:4200/static/images/img/flag-rf.jpg");background-repeat:no-repeat;background-size:cover;background-position:center center;margin:0;display:flex;justify-content:center;padding-top:55mm;position:relative}.wrapper{display:flex;flex-direction:column;align-items:center}.title{font-size:48px;margin-bottom:20px}.qr{width:90px;height:90px;position:absolute;left:21px;bottom:21px}.price{font-size:68px;color:#ab2200;padding-left:16px}.price span{font-size:32px}</style></head><body><div class="wrapper"><h1 class="marck-script-regular title">${dto.title}</h1><h2 class="roboto-bold price">${dto.totalPrice}<span>₽</span></h2></div><img class="qr" src="http://localhost:4200/static/images/qr/${dto.id}.png" alt=""></body></html>`
		default:
			return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Marck+Script&family=Roboto:wght@300;400;700&display=swap" rel="stylesheet"><title>Certificate</title><style type="text/css">@page{size:A5 landscape;margin:0}.marck-script-regular{font-family:'Marck Script',cursive;font-weight:400;font-style:normal}.roboto-light{font-family:Roboto,sans-serif;font-weight:300;font-style:normal}.roboto-regular{font-family:Roboto,sans-serif;font-weight:400;font-style:normal}.roboto-bold{font-family:Roboto,sans-serif;font-weight:700;font-style:normal}*{margin:0;padding:0;box-sizing:border-box}html{background:#eee}body{box-sizing:border-box;height:148mm;width:210mm;background-image:url("http://localhost:4200/static/images/img/bg-certificate.jpg");background-repeat:no-repeat;background-size:cover;background-position:center center;margin:0;display:flex;justify-content:center;padding-top:55mm;position:relative}.wrapper{display:flex;flex-direction:column;align-items:center}.title{font-size:48px;margin-bottom:20px}.qr{width:90px;height:90px;position:absolute;left:21px;bottom:21px}.price{font-size:68px;color:#ab2200;padding-left:16px}.price span{font-size:32px}</style></head><body><div class="wrapper"><h1 class="marck-script-regular title">${dto.title}</h1><h2 class="roboto-bold price">${dto.totalPrice}<span>₽</span></h2></div><img class="qr" src="http://localhost:4200/static/images/qr/${dto.id}.png" alt=""></body></html>`
	}
}
